### ISSUE TITLE
Minor release for translation fix

### ISSUE THREAD

**Issue by victorhporto** [epoberezkin/ajv-i18n#114]
Hi! First of all, thanks for the awesome library! 

I need some pt-BR translations that are missing in the latest release, but were already merged to master with commit https://github.com/epoberezkin/ajv-i18n/commit/7a7ec6e0b99ebd3385f140dbb419584e1535979e.

Is it possible to generate a minor release with these changes, so I can install via npm ? Thanks!

**Comment by epoberezkin** [comment]
v3.5.0
